Repository DSMJung/cheajib-server, pull requests merged in 2022-09, with the labels that each got.

#12 🔀 :: (#10) error setting
  src/main/kotlin/com/cheajib/cheajibserver/global/error/ExceptionFilter.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/GlobalException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/CustomConstraintViolationException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/CustomDataIntegrityViolationException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/CustomIllegalArgumentException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/CustomMethodArgumentNotValidException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/InternalServerError.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/propertys/ErrorProperty.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/propertys/ErrorResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/propertys/GlobalErrorCode.kt
Labels: 기능 추가, 프로젝트 설정

#15 🔀 :: (#13) Restaur Entity 생성
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/DependencyVersion.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/Restaurant.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/repository/RestaurantRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/entity/BaseTimeEntity.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/entity/BaseUUIDEntity.kt
Labels: 기능 추가

#17 🔀 :: (#16) 유저 entity 생성
  build.gradle.kts
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/User.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/type/Level.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/type/Sex.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/ExceptionFilter.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/GlobalException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/CustomConstraintViolationException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/CustomDataIntegrityViolationException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/CustomIllegalArgumentException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/CustomMethodArgumentNotValidException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/exception/InternalServerError.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/properties/ErrorProperty.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/properties/ErrorResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/properties/GlobalErrorCode.kt
Labels: 기능 추가

#22 🔀 :: (#21) 여러 엔티티 생성
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Comment.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/CommentRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/ReviewImageRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/ReviewRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Review.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/ReviewImage.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/User.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/repository/UserRepository.kt
Labels: 기능 추가

#23 🔀 :: (#20) owner entity
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/Owner.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/repository/OwnerRepository.kt
  src/main/resources/application.yml
Labels: 기능 추가

#27 🔀 :: (#25) menu registation
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/Menu.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/presentation/MenuController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/presentation/dto/request/RegisterMenuRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/service/RegisterMenuService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/exception/RestaurantNotFoundException.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/exception/properties/RestaurantErrorCode.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/facade/RestaurantFacade.kt
Labels: 기능 추가

#31 🔀 :: (#30) 메뉴 삭제하기
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/exception/MenuNotFoundException.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/exception/properties/MenuErrorCode.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/facade/MenuFacade.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/presentation/MenuController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/service/DeleteMenuService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/service/RegisterMenuService.kt
Labels: 기능 추가

#29 🔀 :: (#26) Security Setting
  buildSrc/src/main/kotlin/Dependency.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/exception/UserNotFoundException.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/exception/properties/UserErrorProperty.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/facade/UserFacade.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/SecurityConfig.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/auth/AuthDetails.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/auth/AuthDetailsService.kt
Labels: 기능 추가

#32 🔀 :: (#14) OAuth2 로그인 / 회원가입 Api
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/DependencyVersion.kt
  src/main/kotlin/com/cheajib/cheajibserver/CheajibServerApplication.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/Menu.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/Restaurant.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/controller/OauthController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/Owner.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/User.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/type/Sex.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/service/NaverOauthService.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/entity/BaseUUIDEntity.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/error/properties/GlobalErrorCode.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/SecurityConfig.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/auth/AuthDetails.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/aws/config/S3Config.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/aws/exception/ImageNotFoundException.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/aws/exception/InvalidImageExtensionFormatException.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/aws/facade/ImageFacade.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/client/NaverTokenClient.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/client/NaverUserInfoClient.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/config/FeignConfig.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/dto/response/NaverUserInfoElement.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/dto/response/TokenResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/dto/response/UserInfoResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/error/FeignClientErrorDecoder.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/exception/FeignBadRequestException.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/exception/FeignExpiredTokenException.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/exception/FeignForbiddenException.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/exception/FeignUnAuthorizedException.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/properties/GoogleFeignProperties.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/feign/properties/NaverFeignProperties.kt
  src/main/resources/application.yml
Labels: chore, 기능 추가, 리펙토링

#34 🔀 :: (#28) 리뷰 작성하기
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/Menu.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/repository/MenuRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/facade/MenuFacade.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/presentation/dto/request/RegisterMenuRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/service/DeleteMenuService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/service/RegisterMenuService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Review.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/ReviewController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/dto/request/WriteReviewRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/dto/response/MenuInfoElement.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/service/WriteReviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/facade/UserFacade.kt
Labels: chore, 기능 추가

#37 🔀 :: (#35) CD 설정
  .github/workflows/CD.yml
  Dockerfile
Labels: 기능 추가, 프로젝트 설정

#41 🔀 :: (#40) 이미지 업로드 API
  src/main/kotlin/com/cheajib/cheajibserver/domain/image/controller/ImageController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/image/controller/dto/response/ImageListResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/image/service/ImageService.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/SecurityConfig.kt
  src/main/kotlin/com/cheajib/cheajibserver/infrastructure/aws/facade/ImageFacade.kt
  src/main/resources/application.yml
Labels: 기능 추가

#45 🔀 :: (#44) 사장님 리뷰 댓글 작성 Api
  src/main/kotlin/com/cheajib/cheajibserver/domain/comment/domain/Comment.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/comment/domain/repository/CommentRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/comment/presentation/CommentController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/comment/presentation/dto/request/WriteCommentReviewRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/comment/service/WriteCommentReviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/exception/ReviewErrorCode.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/exception/ReviewNotFoundException.kt
Labels: 기능 추가

#43 🔀 :: (#42) 사장님 인증 Api
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/domain/Owner.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/domain/repository/OwnerRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/presentation/OwnerController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/presentation/dto/request/VerifyOwnerRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/service/OwnerService.kt
Labels: 기능 추가

#50 🔀 :: (#46) 메뉴 조회 API
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/Menu.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/MenuLevel.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/repository/MenuLevelRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/repository/MenuRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/presentation/MenuController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/presentation/dto/response/MenuElement.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/presentation/dto/response/MenuListResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/service/QueryMenuListService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/service/RegisterMenuService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/service/WriteReviewService.kt
Labels: 기능 추가, 리펙토링

#51 🔀 :: (#24) 채식 단계 설정
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/controller/UserController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/controller/dto/SetVeganLevelRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/User.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/service/SetVeganLevelService.kt
Labels: 기능 추가

#54 🔀 :: (#53) CORS 설정
  src/main/kotlin/com/cheajib/cheajibserver/global/cors/WebMvcConfig.kt
Labels: 프로젝트 설정

#55 🔀 :: (#52) 사장님 승인 Api
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/domain/Owner.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/exception/OwnerNotFoundException.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/exception/error/OwnerErrorCode.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/presentation/OwnerController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/presentation/dto/request/ApproveOwnerRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/service/ApproveOwnerService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/service/VerifyOwnerService.kt
Labels: 기능 추가, 리펙토링

#48 🔀 :: (#33) Jwt Setting
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/RefreshToken.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/configuration/ConfigurationPropertiesScanConfig.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/configuration/FeignClientConfig.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/JwtTokenFilter.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/JwtTokenProvider.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/JwtTokenResolver.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/exception/ExpiredTokenException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/exception/JwtValidateException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/exception/SignatureTokenException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/exception/UnexpectedTokenException.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/exception/properties/JwtErrorCode.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/properties/JwtProperty.kt
Labels: 기능 추가

#58 🔀 :: (#57) 토큰 로직 추가
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/facade/UserFacade.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/service/NaverOauthService.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/jwt/JwtTokenProvider.kt
Labels: 리펙토링

#62 🔀 :: (#60) 메뉴 상세보기 API
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/repository/MenuRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/facade/MenuFacade.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/Restaurant.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/RestaurantController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/dto/response/RestaurantDetailsResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/service/QueryRestaurantDetailsService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Review.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/ReviewController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/service/WriteReviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/presentation/UserController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/presentation/dto/SetVeganLevelRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/service/SetVeganLevelService.kt
  src/main/resources/application.yml
Labels: chore, 기능 추가

#61 🔀 :: (#59) 가게 미리보기
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/repository/MenuLevelRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/menu/domain/repository/MenuRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/Restaurant.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/RestaurantController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/dto/response/MainMenuListResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/dto/response/QueryRestaurantResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/service/QueryRestaurantPreviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/ReviewRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/ReviewController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/User.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/exception/properties/UserErrorProperty.kt
Labels: 기능 추가

#56 🔀 :: (#49) 자신이 작성한 리뷰 보기
  src/main/kotlin/com/cheajib/cheajibserver/domain/comment/domain/Comment.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/comment/service/WriteCommentReviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/CustomReviewRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/CustomReviewRepositoryImpl.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/ReviewRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/vo/MyReviewVO.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/vo/OwnerCommentVO.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Review.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/ReviewController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/dto/response/MyReviewListResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/dto/response/MyReviewResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/dto/response/OwnerCommentResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/service/QueryMyReviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/service/WriteReviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/config/QuerydslConfig.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/entity/BaseTimeEntity.kt
Labels: chore, 기능 추가, 리펙토링

#67 🔀 :: (#60) 가게 리뷰 보기 & 가게 상세보기 수정
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/repository/CustomRestaurantRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/repository/CustomRestaurantRepositoryImpl.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/repository/RestaurantRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/repository/vo/ReviewCommentVO.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/repository/vo/ReviewVO.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/RestaurantController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/dto/response/QueryRestaurantReviewResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/dto/response/QueryReviewCommentResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/dto/response/QueryReviewResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/service/QueryRestaurantDetailsService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/service/QueryRestaurantPreviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/service/QueryRestaurantReviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/ReviewRepository.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/facade/ReviewFacade.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/service/QueryMyReviewService.kt
Labels: chore, 기능 추가, 리펙토링

#70 🔀 :: (#69) 가게 정보 보기
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/domain/Restaurant.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/RestaurantController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/presentation/dto/response/QueryRestaurantInfoResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/restaurant/service/QueryRestaurantInfoService.kt
Labels: 기능 추가

#72 🔀 :: (#71) 채식 단계 보기
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/presentation/UserController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/presentation/dto/request/SetVeganLevelRequest.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/presentation/dto/response/QueryVeganLevelResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/service/QueryVeganLevelService.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/service/SetVeganLevelService.kt
Labels: chore, 기능 추가

#74 🔀 :: (#73) 자신의 정보 보기
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/presentation/UserController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/presentation/dto/response/QueryMyInfoResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/user/service/QueryMyInfoService.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/SecurityConfig.kt
Labels: chore, 기능 추가

#76 🔀 :: (#75) 사장님 확인 API
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/presentation/OwnerController.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/presentation/dto/response/CheckOwnerResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/owner/service/CheckOwnerService.kt
Labels: 기능 추가

#78 🔀 :: (#77) 자신이 작성한 리뷰 보기에서 이미지 추가하기
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/CustomReviewRepositoryImpl.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/domain/Repository/vo/MyReviewVO.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/presentation/dto/response/MyReviewResponse.kt
  src/main/kotlin/com/cheajib/cheajibserver/domain/review/service/QueryMyReviewService.kt
  src/main/kotlin/com/cheajib/cheajibserver/global/security/SecurityConfig.kt
Labels: chore, 버그
